# This is a config for E2B sandbox template.
# You can use template ID (f57luesnc366ong9ummz) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("f57luesnc366ong9ummz") # Sync sandbox
# sandbox = await AsyncSandbox.create("f57luesnc366ong9ummz") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('f57luesnc366ong9ummz')

team_id = "adba0070-5441-46b9-abf5-774713f5577c"
start_cmd = "/root/.jupyter/start-up.sh"
dockerfile = "e2b.Dockerfile"
template_id = "f57luesnc366ong9ummz"
